server:
  port: 8081
spring:
  application:
    name: order-service    # should same source of truth for properties
                           # ex-> order-service.yml , order-service-dev.yml
  profiles:
    active: dev
  config:
    import: "configserver:http://localhost:8888"


